# Generated by Django 2.0.3 on 2018-03-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song_sim_matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song1', models.CharField(max_length=32, null=True)),
                ('song2', models.CharField(max_length=32, null=True)),
                ('song3', models.CharField(max_length=32, null=True)),
                ('song4', models.CharField(max_length=32, null=True)),
                ('song5', models.CharField(max_length=32, null=True)),
                ('song6', models.CharField(max_length=32, null=True)),
                ('song7', models.CharField(max_length=32, null=True)),
                ('song8', models.CharField(max_length=32, null=True)),
                ('song9', models.CharField(max_length=32, null=True)),
                ('song10', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
